# Generated by Django 3.1.2 on 2020-11-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20201113_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='content_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
