# Generated by Django 3.1.2 on 2020-11-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_restaurant_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default="your restaurant's description", max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default="your restaurant's location", max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default="your restaurant's name", max_length=200),
        ),
    ]
