# Generated by Django 3.1.2 on 2020-11-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201113_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='deliveryTime',
            field=models.CharField(default='Estimated time?', max_length=200),
        ),
    ]
