# Generated by Django 3.1.3 on 2020-11-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_addressprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressprofile',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
