# Generated by Django 3.1.2 on 2020-12-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20201129_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_photo',
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.FileField(blank=True, default=None, upload_to='reviewImages/'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, default=None, upload_to='')),
                ('content_type', models.CharField(default='', max_length=50)),
                ('review', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.review')),
            ],
        ),
    ]
