# Generated by Django 3.1.2 on 2020-12-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20201201_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='images',
            field=models.FileField(blank=True, default=None, upload_to='reviewImages/'),
        ),
    ]
