# Generated by Django 3.1.2 on 2020-12-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20201201_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewimage',
            old_name='images',
            new_name='image',
        ),
    ]
