# Generated by Django 3.1.2 on 2020-12-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20201201_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='num_review',
            field=models.IntegerField(default=0),
        ),
    ]
