# Generated by Django 3.1.1 on 2020-12-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_restaurant_num_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('entry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.entry')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.order')),
            ],
        ),
    ]
