# Generated by Django 3.1.2 on 2020-12-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20201204_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='project.addressprofile'),
        ),
    ]
