# Generated by Django 3.1.4 on 2020-12-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20201205_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('Appetizer', 'Appetizer'), ('Soup', 'Soup'), ('Salad', 'Salad'), ('Entree', 'Entree'), ('Beverage', 'Beverage'), ('Dessert', 'Dessert')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
